algoritmo "video 09-4 ler 5 numeros e soma-los"
// somador numerico
//Curso de Algoritmos #09
//Estruturas de Repetição 1
// pratica 04

var

n, soma: inteiro
resp: caracter
inicio

soma <- 0
resp <- "S"
     enquanto (resp = "S") faca
     escreva ("Digite o um valor: ")
     leia (n)
     soma <- soma + n
     escreva ("Voce quer continuar [S/N]")
     leia (resp)

     fimenquanto

     escreval (" a soma de todos os valores foi ", soma)
fimalgoritmo