Algoritmo "05"
// Disciplina   : [Algoritmos]
// Professor   : Andréia Machado
// Descrição   : Escreva um Algoritmo que leia nome e sobrenome do aluno, depois imprima na tela"
// Autor(a)    : Ricardo
// Data atual  : 16/04/2021


Var
Nome, Sobrenome: caracter

Inicio
	escreval ("Digite o nome do aluno")
    leia (Nome)
 
	escreval ("Digite o sobrenome do aluno")
	leia (Sobrenome)

 escreval ("O nome completo é: " ,Nome, " ",Sobrenome)


Fimalgoritmo