algoritmo "video 09-4 ler 10 numeros e soma-los"
// somador numerico
//Curso de Algoritmos #09
//Estruturas de Repetição 1
// pratica 04

var

cont, n, soma: inteiro

inicio

cont <- 1
soma <- 0
     enquanto (cont<= 10) faca
     escreva ("Digite o ", cont,  "o. valor: ")
     leia (n)
     soma <- soma + n
     cont <- cont +1

     fimenquanto

     escreval (" a soma de todos os valores foi ", soma)
fimalgoritmo